spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:

          - id: auth-service
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/api/auth/**

          - id: problem-service
            uri: lb://PROBLEM-SERVICE
            predicates:
              - Path=/api/problems/**

          - id: submission-service
            uri: lb://SUBMISSION-SERVICE
            predicates:
              - Path=/api/submissions/**

          - id: judge-service
            uri: lb://JUDGE-SERVICE
            predicates:
              - Path=/api/judge/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

jwt:
  secret: mySuperSecretKeyForCodingJudgePlatform2026MySuperSecretKey