spring:
  application:
    name: submission-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

jwt:
  secret: mySuperSecretKeyForCodingJudgePlatform2026MySuperSecretKey

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

resilience4j:
  retry:
    instances:
      judgeRetry:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - feign.FeignException

  circuitbreaker:
    instances:
      judgeService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

logging:
  level:
    io.github.resilience4j.retry: TRACE
    io.github.resilience4j.circuitbreaker: DEBUG