spring:
  kafka:
    bootstrap-servers: kafka:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: submission-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.anshu.codingjudge.submissionservice.dto.kafka.JudgeResultEvent

  application:
    name: submission-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

jwt:
  secret: mySuperSecretKeyForCodingJudgePlatform2026MySuperSecretKey

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

resilience4j:
  retry:
    instances:
      judgeRetry:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - feign.FeignException

  circuitbreaker:
    instances:
      judgeService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

logging:
  level:
    io.github.resilience4j.retry: TRACE
    io.github.resilience4j.circuitbreaker: DEBUG